config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  resources :users, only: %i[show edit update] do
    resources :follows, only: %i[create destroy]
  end

  resources :tweets , except: %i[edit update show] do
    resources :likes, only: %i[new create destroy]
    resources :comments, except: %i[edit update show destroy]
    resources :retweets, only: %i[new create]
  end
 
  namespace :explore do
    resources :tweets, only: :index
  end

  namespace :notifications do
    resources :tweets, only: :index
  end

  root "tweets#index"
end

app/controllers/retweets_controller.rb
class RetweetsController < ApplicationController
  before_action :extract_mentions_and_tags, only: :create

  def new
    @tweet = Tweet.find(params[:tweet_id])
    @retweet = @tweet.retweets.new()
  end

  def create 
    tweet = Tweet.find(params[:tweet_id])
    @retweet = tweet.retweets.new(retweet_params)
    if @retweet.save
      redirect_to root_path
    else 
      render :new, status: :unprocessable_entity
    end
  end

  private
  def retweet_params
    permitted_params = params.permit(:content, :tweet_type)
    
    permitted_params.merge!(user_id: current_user.id)
  end 
end

app/helpers/retweets_helper.rb
module RetweetsHelper
end

app/views/retweets/_retweet.html.slim
div class='tweet__body'
  - if retweet.user.avatar.attached?
    = image_tag retweet.user.avatar, class:'tweet_avatar'
  - else 
    = image_tag 'profile.svg', class:'tweet_avatar'
  = link_to retweet.user.handle, user_path(retweet.user), data: {turbo_frame: :content, turbo_action: :advance}
  = raw retweet.content
- if current_user == retweet.user
  = link_to 'Delete', tweet_path(retweet), data: { turbo_method: :delete} 
br

div class='retweet__body'
  - if retweet.tweet.user.avatar.attached?
    = image_tag retweet.tweet.user.avatar, class:'tweet_avatar'
  - else 
    = image_tag 'profile.svg', class:'tweet_avatar'
  = link_to retweet.tweet.user.handle, user_path(retweet.tweet.user), data: {turbo_frame: :content, turbo_action: :advance}
  = raw retweet.tweet.content

= link_to 'Delete', tweet_path(retweet), data: { turbo_method: :delete} 
br

div class='tweet__icons'
  = turbo_frame_tag "like_tweet_#{retweet.id}", src: new_tweet_like_path(retweet, type:'tweet')
  div class='icon__set'
    = link_to new_tweet_retweet_path(retweet), data:{turbo_frame: :modal} do 
      = image_tag 'retweet.svg', class:'icon'
    = retweet.retweets.count

  div class='icon__set'
    = link_to new_tweet_comment_path(retweet), data: {turbo_frame: :modal} do 
      = image_tag 'comment.svg', class:'icon'
    = retweet.comments.count
- if retweet.comments.present?
  div class='comments'
    = turbo_frame_tag "tweet_#{retweet.id}_comments", src: tweet_comments_path(retweet)

app/views/retweets/new.html.slim
= turbo_frame_tag 'modal'
  div class='modal'
    div class='modal__inner'
      = form_with url: tweet_retweets_path(@retweet.tweet), data:{turbo_frame: :content, controller: 'modal', \
                                                action: 'turbo:submit-end->modal#close'} do |form|
        div class='modal__header'
          h3 Retweet
          button type="button" data-action="click->modal#close"
            = image_tag 'close.svg', class:'icon'

        = form.hidden_field :tweet_type , value: 'retweet'
        div 
          = form.label :content
          = form.rich_text_area :content
        div 
          = raw @retweet.tweet.content
        div 
          = form.submit 'Retweet'