config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  resources :users, only: %i[show edit update] do
    resources :follows, only: %i[create destroy]
  end

  resources :tweets , except: %i[edit update show] do
    resources :likes, only: %i[new create destroy]
    resources :comments, except: %i[edit update show destroy]
    resources :retweets, only: %i[new create]
  end
 
  namespace :explore do
    resources :tweets, only: :index
  end

  namespace :notifications do
    resources :tweets, only: :index
  end

  root "tweets#index"
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def new
    @tweet = Tweet.find(params[:tweet_id])
    @like = current_user.likes.find_or_initialize_by(tweet_id: @tweet.id)
  end

  def create
    @like = current_user.likes.new(like_params)
    if @like.save
      redirect_to new_tweet_like_path(@like.tweet, type: params[:type]), status: :see_other
    else
      render :new, status: :unprocessable_entity
    end
      
  end

  def destroy
    begin
      @tweet = Tweet.find(params[:tweet_id])
      @like = @tweet.likes.find(params[:id])

      @like.destroy
      redirect_to new_tweet_like_path(@tweet, type: params[:type]), status: :see_other
    rescue  ActiveRecord::RecordNotDestroyed, ActiveRecord::RecordNotFound
      render :new, status: :unprocessable_entity
    end
  end

  private
  def like_params
    params.permit(:tweet_id)
  end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_comment.html.slim
= turbo_frame_tag "like_comment_#{tweet.id}"
  - if @tweet.liked?(current_user)
      = link_to tweet_like_path(tweet, tweet.likes.find_by(tweet_id: tweet.id), type: 'comment'), data: {turbo_method: :delete} do 
        = image_tag 'unlike.svg', class:'icon'
  -else 
    = link_to tweet_likes_path(tweet, type: 'comment'), data: {turbo_method: :post} do 
      = image_tag 'like.svg', class:'icon'
  = render 'likes', likes: @tweet.likes

app/views/likes/_likes.html.slim
=likes.count

app/views/likes/_tweet.html.slim
= turbo_frame_tag "like_tweet_#{tweet.id}"
  div class='icon__set'
    - if @tweet.liked?(current_user)
        = link_to tweet_like_path(tweet, tweet.likes.find_by(tweet_id: tweet.id), type: 'tweet'), data: {turbo_method: :delete} do 
          = image_tag 'unlike.svg', class:'icon'
    -else 
      = link_to tweet_likes_path(tweet, type: 'tweet'), data: {turbo_method: :post} do 
        = image_tag 'like.svg', class:'icon'
    = render 'likes', {likes: tweet.likes, tweet_type: tweet.tweet_type}

app/views/likes/new.html.slim
= render params[:type], {tweet: @tweet, like: @like, current_user: current_user}

  