config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  resources :users, only: %i[show edit update] do
    resources :follows, only: %i[create destroy]
  end

  resources :tweets , except: %i[edit update show] do
    resources :likes, only: %i[new create destroy]
    resources :comments, except: %i[edit update show destroy]
    resources :retweets, only: %i[new create]
  end
 
  namespace :explore do
    resources :tweets, only: :index
  end

  namespace :notifications do
    resources :tweets, only: :index
  end

  root "tweets#index"
end

app/models/user.rb
class User < ApplicationRecord
  devise  :database_authenticatable, 
          :registerable, 
          :recoverable, 
          :rememberable, 
          :validatable,
          :confirmable

  has_many :tweets , dependent: :destroy
  has_many :likes, dependent: :destroy
  
  has_many :followers, foreign_key: 'followee_id', class_name: 'Follow'
  has_many :followees, foreign_key: 'follower_id', class_name: 'Follow'

  has_many :taggings
  has_many :tags, through: :taggings, dependent: :destroy
  accepts_nested_attributes_for :tags, allow_destroy: true
  
  has_many :mentions, foreign_key: :user_name, primary_key: :handle

  validates :first_name, presence: true
  validates :last_name,  presence: true
  validates :phone,      presence: true
  validates :description, length: { maximum: 300 }
  
  has_one_attached :avatar
  has_one_attached :background_image

  def tags_attributes=(tags_attributes)
    self.tags = Tag.where_or_create(tags_attributes)
  end

  def following(followee_id)
    followees.find_by(followee_id: followee_id).present?
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]

  def new
    build_resource({})
    5.times {resource.tags.build}
    respond_with resource
  end

  protected

  def sign_up_params
    devise_parameter_sanitizer.sanitize(:sign_up) { |user| user.permit(permitted_attributes) }
  end

  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: permitted_attributes)
  end

  def permitted_attributes
    [
      :email,
      :password,
      :password_confirmation,
      :remember_me,
      :role,
      :first_name, 
      :last_name, 
      :phone,
      :description, 
      :avatar,
      :handle,
      tags_attributes:  :body
    ]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @tweets = @user.tweets.created_at_desc
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.taggings.destroy_all
    if @user.update(user_params)
      redirect_to @user 
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private
  def user_params
    params.require(:user).permit( :first_name, :last_name, :background_image, :avatar, :description, :handle, :phone, tags_attributes: :body)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.slim
= turbo_frame_tag 'modal'
  div class='modal'
    div class='modal__inner'
      = form_with model: @user, data:{turbo_frame: 'page-content', controller: 'modal', \
                                                action: 'turbo:submit-end->modal#close'} do |form|
        
        button type="button" data-action="click->modal#close"
          = image_tag 'close.svg', class:'icon'
        div
          = form.label :background_image
          br
          = form.file_field :background_image, accept: 'image/png, image/gif, image/jpeg'
        div
          = form.label :avatar
          br
          = form.file_field :avatar, accept: 'image/png, image/gif, image/jpeg'
        div
          = form.text_field :first_name, placeholder: 'First name'
        div 
          = form.text_field :last_name, placeholder: 'Last name'
        div 
          = form.telephone_field :phone, placeholder: 'phone number'
        div 
          = form.text_field :handle
        div 
          = form.text_area :description, placeholder: 'Bio'
        h3 Tags
        = form.fields_for :tags do |tags_form|
          div 
            = tags_form.text_field :body
        div 
          = form.submit 'Update profile'

app/views/users/show.html.slim
=turbo_frame_tag 'page-content'
  div class='user-header'
    - if @user.background_image.attached?
      = image_tag @user.background_image, class:'background-header'
    - else 
      = image_tag 'background_default.svg', class:'background-header'
    - if @user.avatar.attached?
       = image_tag @user.avatar, class:'avatar'
    - else 
      = image_tag 'profile.svg', class:'avatar'

    h1 #{@user.first_name} #{@user.last_name}
    p #{@user.description}
    - if current_user == @user
      = link_to 'edit profile', edit_user_path(@user), data: {turbo_frame: :modal}
      h3 class='user__tags' Tags
      div class='user__tags'
        - @user.tags.each do |tag|
          p #{tag.body}
    - else 
      -if !current_user.following(@user.id)
        = link_to 'Follow', user_follows_path(@user), data: {turbo_method: :post}
      -else
        = link_to 'Unfollow', user_follow_path(@user, 0), data: {turbo_method: :delete}

  = turbo_stream_from 'tweets'
  div id='tweets'
    = render @tweets
    
    